workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "continuous-integration-setup" && $CI_PIPELINE_SOURCE == "push"

build-and-test-frontend:
  trigger:
    include:
       - local: ci-templates/frontend-ci.yml
