module.exports = {
    "testObject":
    {
        firstName: "David",
        middleName: "Naval",
        lastName: "Cotton",
        dob: "2000-09-02",
        street: "3452 Somewhere",
        city: "Ground",
        state: "IA",
        zip: "64543",
        userName: "idontknowmuch@school.edu",
        testPass: "none",
        passport: "984b9db9",
        driverID: "yyyyyyyy",
        securityAnswer: "Summer City",
        email: "idontknowmuch@school.edu",
        employeeID: "NoSQLAlchemy",
        role: "Manager",
        name: "David Naval Cotton",
        stationID: "52317-6757",
        stationIDInput: "LA-42",
        headEmail: "mcdonald.tesla@gmail.com",
        address: "7867 York Avenue, New York City, NY 67622",
        geographyID: "New York City-Manhattan-NY",
        districtID: "IA-SN-1",
        covers: "67622",
        title: "Iowa Senate Seat 9",
        type: "IA-SENATE",
        term: "2024-2028",
        districtID: "IA-SN-9",
        electionID: "IA-2024",
        officialID: "THOMPSON-IA-576"
    }
} 
